ROLE_TRANSLATOR = 'translator'
ROLE_DEVELOPER = 'developer'
ROLE_MANAGER = 'manager'
ROLE_OWNER = 'owner'

ROLE_PRIORITY_MAP = {
    'translator': 1,
    'developer': 2,
    'manager': 3,
    'owner': 4
}.freeze

ROLES_TRANSLATOR_UP = [ROLE_TRANSLATOR, ROLE_DEVELOPER, ROLE_MANAGER, ROLE_OWNER]
ROLES_DEVELOPER_UP = [ROLE_DEVELOPER, ROLE_MANAGER, ROLE_OWNER]
ROLES_MANAGER_UP = [ROLE_MANAGER, ROLE_OWNER]
ROLES_OWNER_UP = [ROLE_OWNER]

ROLES_BELOW_TRANSLATOR = []
ROLES_BELOW_DEVELOPER = [ROLE_TRANSLATOR]
ROLES_BELOW_MANAGER = [ROLE_TRANSLATOR, ROLE_DEVELOPER]
ROLES_BELOW_OWNER = [ROLE_TRANSLATOR, ROLE_DEVELOPER, ROLE_MANAGER]
