ROLE_TRANSLATOR = 'translator'
ROLE_DEVELOPER = 'developer'
ROLE_MANAGER = 'manager'
ROLE_OWNER = 'owner'

ROLES_TRANSLATOR_UP = [ROLE_TRANSLATOR, ROLE_DEVELOPER, ROLE_MANAGER, ROLE_OWNER]
ROLES_DEVELOPER_UP = [ROLE_DEVELOPER, ROLE_MANAGER, ROLE_OWNER]
ROLES_MANAGER_UP = [ROLE_MANAGER, ROLE_OWNER]
