/**
 * Txty API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostActivateUserResponse {
  error?: boolean;
  details?: string;
}


export interface PostDeactivateUserResponse {
  error?: boolean;
  details?: string;
}

