export type IFeature =
    | "FEATURE_VALIDATIONS"
    | "FEATURE_KEY_HISTORY"
    | "FEATURE_EXPORT_HIERARCHY"
    | "FEATURE_POST_PROCESSING"
    | "FEATURE_PROJECT_ACTIVITY"
    | "FEATURE_TAG_MANAGEMENT"
    | "FEATURE_ADVANCED_PERMISSION_SYSTEM"
    | "FEATURE_OTA"
    | "FEATURE_HTML_EDITOR"
    | "FEATURE_TEMPLATES"
    | "FEATURE_PROJECT_GROUPS"
    | "FEATURE_MACHINE_TRANSLATIONS";
