export type IFeature =
    | "FEATURE_VALIDATIONS"
    | "FEATURE_KEY_HISTORY"
    | "FEATURE_EXPORT_HIERARCHY"
    | "FEATURE_POST_PROCESSING"
    | "FEATURE_PROJECT_ACTIVITY"
    | "FEATURE_OVER_THE_AIR"
    | "FEATURE_HTML_EDITOR"
    | "FEATURE_MACHINE_TRANSLATION_SUGGESTIONS"
    | "FEATURE_MACHINE_TRANSLATION_LANGUAGE"
    | "FEATURE_MACHINE_TRANSLATION_AUTO_TRANSLATE"
    | "FEATURE_TAGS";
